"""Formats raw TradingAgents output into readable daily reports."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


def _section(title: str, width: int = 72) -> str:
    return f"\n{'=' * width}\n  {title}\n{'=' * width}\n"


def _subsection(title: str, width: int = 72) -> str:
    return f"\n{'-' * width}\n  {title}\n{'-' * width}\n"


def format_single_ticker(ticker: str, state: Dict[str, Any], decision: str) -> str:
    """Format analysis results for a single ticker into readable text."""
    lines = []
    lines.append(_subsection(f"{ticker}  —  Recommendation: {decision.strip().upper()}"))

    # Analyst reports
    for label, key in [
        ("Market / Technical Analysis", "market_report"),
        ("Fundamentals Analysis", "fundamentals_report"),
        ("News Analysis", "news_report"),
        ("Social Sentiment Analysis", "sentiment_report"),
    ]:
        report = state.get(key, "")
        if report:
            lines.append(f"\n  [{label}]")
            lines.append(f"  {report.strip()}\n")

    # Investment debate summary
    debate = state.get("investment_debate_state", {})
    judge = debate.get("judge_decision", "")
    if judge:
        lines.append(f"\n  [Investment Debate Conclusion]")
        lines.append(f"  {judge.strip()}\n")

    # Trader plan
    trader_plan = state.get("trader_investment_plan", "")
    if trader_plan:
        lines.append(f"\n  [Trader Investment Plan]")
        lines.append(f"  {trader_plan.strip()}\n")

    # Risk debate summary
    risk = state.get("risk_debate_state", {})
    risk_judge = risk.get("judge_decision", "")
    if risk_judge:
        lines.append(f"\n  [Risk Assessment Conclusion]")
        lines.append(f"  {risk_judge.strip()}\n")

    # Final decision
    final = state.get("final_trade_decision", "")
    if final:
        lines.append(f"\n  [Final Trade Decision]")
        lines.append(f"  {final.strip()}\n")

    return "\n".join(lines)


def format_daily_report(
    results: List[Dict[str, Any]],
    trade_date: str,
) -> str:
    """Build the full daily report from a list of per-ticker results.

    Each element of *results* is a dict with keys:
        ticker, state, decision, error (optional)
    """
    lines = []
    lines.append(_section(f"DAILY STOCK RECOMMENDATIONS  —  {trade_date}"))
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"  Tickers analysed: {len(results)}\n")

    # Quick summary table
    lines.append(_subsection("SUMMARY"))
    lines.append(f"  {'Ticker':<10} {'Recommendation':<16}")
    lines.append(f"  {'------':<10} {'--------------':<16}")
    for r in results:
        rec = r.get("decision", "ERROR").strip().upper() if not r.get("error") else "ERROR"
        lines.append(f"  {r['ticker']:<10} {rec:<16}")

    # Detailed per-ticker sections
    lines.append(_section("DETAILED ANALYSIS"))
    for r in results:
        if r.get("error"):
            lines.append(_subsection(f"{r['ticker']}  —  ERROR"))
            lines.append(f"  {r['error']}\n")
        else:
            lines.append(format_single_ticker(r["ticker"], r["state"], r["decision"]))

    # Disclaimer
    lines.append(_section("DISCLAIMER"))
    lines.append(
        "  This report is generated by an AI system and is for informational\n"
        "  purposes only. It does NOT constitute financial, investment, or\n"
        "  trading advice. Always do your own research and consult a licensed\n"
        "  financial advisor before making investment decisions.\n"
    )

    return "\n".join(lines)


def save_report(report_text: str, results: List[Dict[str, Any]],
                trade_date: str, reports_dir: str,
                save_json: bool = True, save_text: bool = True) -> Dict[str, str]:
    """Persist the report to disk. Returns dict of saved file paths."""
    out_dir = Path(reports_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    saved = {}

    date_slug = trade_date.replace("-", "")

    if save_text:
        txt_path = out_dir / f"recommendations_{date_slug}.txt"
        txt_path.write_text(report_text)
        saved["text"] = str(txt_path)

    if save_json:
        # Serialise only the parts we need (states contain non-serialisable objects)
        json_results = []
        for r in results:
            entry = {"ticker": r["ticker"], "decision": r.get("decision", "")}
            if r.get("error"):
                entry["error"] = r["error"]
            else:
                state = r["state"]
                entry["reports"] = {
                    "market": state.get("market_report", ""),
                    "fundamentals": state.get("fundamentals_report", ""),
                    "news": state.get("news_report", ""),
                    "sentiment": state.get("sentiment_report", ""),
                }
                entry["final_trade_decision"] = state.get("final_trade_decision", "")

                debate = state.get("investment_debate_state", {})
                entry["investment_debate_conclusion"] = debate.get("judge_decision", "")

                risk = state.get("risk_debate_state", {})
                entry["risk_assessment_conclusion"] = risk.get("judge_decision", "")

            json_results.append(entry)

        json_path = out_dir / f"recommendations_{date_slug}.json"
        json_path.write_text(json.dumps(json_results, indent=2, default=str))
        saved["json"] = str(json_path)

    return saved
